def main_menu():
    print("\n=== RASIS GROUP COMUNISM ===")
    print("\n=== MENU INVENTARIS ===")
    print("1. Tambah Barang")
    print("2. Lihat Barang")
    print("3. Lihat Barang By ID")
    print("4. Edit Barang")
    print("5. Hapus Barang")
    print("6. Keluar")
    return input("Pilih menu (1-6): ")